// Center of the seed area: Mission District, San Francisco.
const CENTER = { latitude: 37.7599, longitude: -122.4148 }

const offset = (dLat, dLng) => ({
  latitude: CENTER.latitude + dLat,
  longitude: CENTER.longitude + dLng,
})

const hoursAgo = (h) => new Date(Date.now() - h * 60 * 60 * 1000).toISOString()
const daysAgo = (d) => hoursAgo(d * 24)

export const SEED_CATS = [
  {
    id: 'cat-1',
    name: 'Marmalade',
    status: 'stray_resident',
    description: 'Orange tabby, friendly, hangs out near the community garden.',
    temperament: 'friendly',
    needs_medical_attention: false,
    medical_details: null,
    primary_photo_url: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400',
    created_at: daysAgo(40),
    updated_at: daysAgo(1),
  },
  {
    id: 'cat-2',
    name: 'Shadow',
    status: 'stray_resident',
    description: 'Black shorthair, part of the alley colony behind the laundromat.',
    temperament: 'skittish',
    needs_medical_attention: false,
    medical_details: null,
    primary_photo_url: 'https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=400',
    created_at: daysAgo(90),
    updated_at: daysAgo(3),
  },
  {
    id: 'cat-3',
    name: 'Unknown Cat',
    status: 'sighted_temporary',
    description: 'Grey and white, seen once near the taqueria dumpsters.',
    temperament: 'unknown',
    needs_medical_attention: false,
    medical_details: null,
    primary_photo_url: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=400',
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: 'cat-4',
    name: 'Biscuit',
    status: 'lost',
    description: 'Cream-colored longhair, microchipped, last seen wearing a blue collar.',
    temperament: 'friendly',
    needs_medical_attention: false,
    medical_details: null,
    primary_photo_url: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=400',
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: 'cat-5',
    name: 'Patches',
    status: 'stray_resident',
    description: 'Calico, feeds at the colony feeding station on 24th St.',
    temperament: 'feral',
    needs_medical_attention: true,
    medical_details: 'Limping on front-right paw, possible thorn or minor injury.',
    primary_photo_url: 'https://images.unsplash.com/photo-1517849845537-4d257902861a?w=400',
    created_at: daysAgo(60),
    updated_at: hoursAgo(6),
  },
  {
    id: 'cat-6',
    name: 'Unknown Cat',
    status: 'found',
    description: 'Small tuxedo kitten, found wandering alone, currently fostered nearby.',
    temperament: 'friendly',
    needs_medical_attention: false,
    medical_details: null,
    primary_photo_url: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=400',
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
]

export const SEED_SIGHTINGS = [
  {
    id: 'sighting-1',
    cat_id: 'cat-1',
    reporter_id: null,
    ...offset(0.0012, -0.0008),
    sighting_time: daysAgo(1),
    photo_url: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400',
    last_fed_date: daysAgo(1),
    notes: 'Fed near the garden gate, very food-motivated.',
    created_at: daysAgo(1),
  },
  {
    id: 'sighting-2',
    cat_id: 'cat-1',
    reporter_id: null,
    ...offset(0.0015, -0.0011),
    sighting_time: daysAgo(6),
    photo_url: null,
    last_fed_date: daysAgo(6),
    notes: 'Sunning on the fence post.',
    created_at: daysAgo(6),
  },
  {
    id: 'sighting-3',
    cat_id: 'cat-2',
    reporter_id: null,
    ...offset(-0.0018, 0.0022),
    sighting_time: daysAgo(3),
    photo_url: 'https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=400',
    last_fed_date: daysAgo(3),
    notes: 'Ran off when approached, stays close to the dumpsters.',
    created_at: daysAgo(3),
  },
  {
    id: 'sighting-4',
    cat_id: 'cat-3',
    reporter_id: null,
    ...offset(0.0005, 0.0031),
    sighting_time: daysAgo(2),
    photo_url: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=400',
    last_fed_date: null,
    notes: 'First time seeing this one, no collar.',
    created_at: daysAgo(2),
  },
  {
    id: 'sighting-5',
    cat_id: 'cat-4',
    reporter_id: null,
    ...offset(-0.0009, -0.0025),
    sighting_time: daysAgo(1),
    photo_url: null,
    last_fed_date: null,
    notes: 'Neighbor reported seeing a cream longhair matching the flyer.',
    created_at: daysAgo(1),
  },
  {
    id: 'sighting-6',
    cat_id: 'cat-5',
    reporter_id: null,
    ...offset(0.0022, 0.0009),
    sighting_time: hoursAgo(6),
    photo_url: 'https://images.unsplash.com/photo-1517849845537-4d257902861a?w=400',
    last_fed_date: hoursAgo(6),
    notes: 'Still limping, watching closely before deciding on a vet trip.',
    created_at: hoursAgo(6),
  },
  {
    id: 'sighting-7',
    cat_id: 'cat-5',
    reporter_id: null,
    ...offset(0.002, 0.0007),
    sighting_time: daysAgo(4),
    photo_url: null,
    last_fed_date: daysAgo(4),
    notes: 'Fed at the usual station.',
    created_at: daysAgo(4),
  },
  {
    id: 'sighting-8',
    cat_id: 'cat-6',
    reporter_id: null,
    ...offset(-0.0031, -0.0014),
    sighting_time: daysAgo(1),
    photo_url: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=400',
    last_fed_date: daysAgo(1),
    notes: 'Now with a foster, doing well.',
    created_at: daysAgo(1),
  },
]
